### ISSUE TITLE
"cwd" must be set

### ISSUE THREAD

**Issue by fmatoss** [coreybutler/node-windows#103]
In latest version (v0.1.9), cwd is now a required Service option, if not set, [wrappers.js line 18](https://github.com/coreybutler/node-windows/blob/master/lib/wrapper.js#L18) will throw "TypeError: Arguments to path.resolve must be strings".

Is this intended? If it is, should be documented.

**Comment by coreybutler** [comment]
@fmatoss - This wasn't intentional and I've pushed a fix to master. I only have my Mac until Monday when I can get back to my Windows machine... if there's any chance you can test this and let me know, I'd appreciate it. Assuming the fixes work, I can push another update today.

**Comment by mmacintosh-ap** [comment]
Tested this by manually editing my wrapper.js. Looks  like you missed a close paren at argv.d)) {. Works after I add the third close paren argv.d))) {. Now I need to see the changes come down via NPM.

**Comment by coreybutler** [comment]
Just pushed `0.1.10`. Thanks for your help @fmatoss!

**Comment by dsandor** [comment]
Thanks for the fix!
