### ISSUE TITLE
Version 1.0.0-beta.2 not creating service

### ISSUE THREAD

**Issue by nejcukmar** [coreybutler/node-windows#266]
Just noticed this started happening yesterday when new lib version came out. (beta.2)

**Issue: Lib says that service has been installed but once you check Services inside windows, it doesn't exist.**

Steps: First time installation goes through and also emits **install** event, which should indicate that the service has been installed. After checking **Services**, there is no service. Also every next install library emits **alreadyinstalled** but again, service still doesn't exist. 
If you downgrade lib version to **beta.1** it works normally.

**Comment by babinskiy** [comment]
Same for me:
neither 'error' nor 'invalidinstallation' event raises, no logs in `daemon` folder creates.

**Comment by tyamz** [comment]
Thank God, I thought something was broken with my installer package, but it seems like this is an issue with the latest version. Shows me for using `npm install` without specifying a version.

**Comment by coreybutler** [comment]
I'm fairly certain the culprit is here: https://github.com/coreybutler/node-windows/commit/5de5dbbb95913c88914d46bdd37b23dfbc7b221a#diff-5c2754430010d5f3e95b45e1bb36d58bL225. I just pushed `beta.3`, which reverts that particular line.

If someone can test this and report back, I would really appreciate it.

**Comment by JSalter02** [comment]
No. beta.3 doesn't fix it (at least for me on Windows 10 Pro).

beta.2 doesn't work either (as previously discussed). Says the service is installed and started, but the service is not listed and does not appear to exist.

beta.1 does work.

Thanks to all for quick replies - I happened to be doing this today and thought it was just me.

**Comment by coreybutler** [comment]
@JSalter02 (or anyone) - the only other code change was the addition of this line: https://github.com/coreybutler/node-windows/commit/5de5dbbb95913c88914d46bdd37b23dfbc7b221a#diff-33dbdab811160c85792ddf82c5546db4R129. If possible, could you remove that line (it will be in `node_modules/node-windows/winsw.js` (line 129).

Beyond those changes, the only other change was removal of the "os" attribute in `package.json` (in https://github.com/coreybutler/node-windows/commit/27644416fb21c145bf0f36dc84ba096532472a51).

**Comment by coreybutler** [comment]
Hold on, I found (and fixed) a regression. Just released as `beta.4`.

**Comment by tallytarik** [comment]
`beta.4` unfortunately not working either. Windows Server 2016.

Reverted to `beta.1` which works as before.

**Comment by tyamz** [comment]
@coreybutler yeah, still having the issue with 4. Appreciate your quick responses though.

**Comment by coreybutler** [comment]
If you open Powershell and run `Get-Process`, can you find your process that way? 

There is an issue with node-mac that revealed an underlying and recurring bug in libuv (present in Node 12 & 14, ok in 13), which prevents process titles from being registered with the Activity Monitor (equivalent of windows Services). I'm starting to wonder if the services are installed and working, just not displaying amongst the services.

Please post which versions of Node you're running.

**Comment by JSalter02** [comment]
The services are not installed and working. Can't reach the node server after it says it is installed and started.

I'm using Node 12.18.3.

**Comment by Perlkonig** [comment]
Running node 12.18.0 + node-windows@1.0.0-beta.4. The install script is indeed throwing all the right events (my `console.log` statements are emitting when they should), but no service is appearing in the service manager or in `Get-Process`, and the app is indeed not running.

**Comment by Perlkonig** [comment]
Rolling back to beta 1 made it start working for me.

**Comment by nvbach91** [comment]
I'm using Node 6.17.1
- `npm install -g node-windows` doesn't create windows service, no error whatsoever during installation
- forcing version `npm install -g node-windows@0.1.14` worked for me

The confusing part is the former worked untill recently. Did the `beta-*` releases mess something up?

**Comment by coreybutler** [comment]
@JSalter02  @Perlkonig Thank you!

@nvbach91 Alot has changed in Windows and in Node. Node 6.x.x has been deprecated for a considerable amount of time now (8.x.x has been deprecated for some time too). Which version of Windows are you running?

**Comment by nvbach91** [comment]
@coreybutler Windows 10 Pro version 2004. I also tried today a fresh installation/reset which ends up with this version.

**Comment by Perlkonig** [comment]
Are you using *Node* version 6 or *npm* version 6? The command you should be typing is `node --version`

**Comment by forty** [comment]
I have the same behavior as @Perlkonig on Windows Server 2019,  12.18.3 

I'll note that reinstalling (svc.install() twice) logs an event saying the service is already installed, so it means it's somehow installed, just it does not appear in the service list for some reasons

**Comment by forty** [comment]
I made some tests, it seems that reverting that change in `winsw.js` made it work again

**Comment by pdfabbro** [comment]
> Thank God, I thought something was broken with my installer package, but it seems like this is an issue with the latest version. Shows me for using `npm i node-windows` without specifying a version.

Same here.  I updated my script to use npm install -g node-windows@0.1.14 until they sort out the kinks.

**Comment by pdfabbro** [comment]
I'm using node v12.16.1 on Windows 2016 server and same issue as others - no error, says service was created, but it doesn't appear in list of services and node server is not running.  I reverted back to 0.1.14 to be safe, but after reading through here maybe i'll try beta1.

**Comment by devcshort** [comment]
- Node v12.18.3
- Windows Server 2019
- Latest version of node-windows

Currently all my service installs with this module will log every event since this is part of an install script. In this case, it reaches the "start" event, but never shows up in the service list and is also unreachable from a web browser.

![image](https://user-images.githubusercontent.com/13677134/88700635-d5a55500-d0bd-11ea-858a-1561d370d890.png)

**Comment by coreybutler** [comment]
Based on @forty's experience, I've made the `allowservicelogin` configuration attribute optional (off by default), as it appears the problem is with the winsw config being generated. There is now a [note](https://github.com/coreybutler/node-windows#user-account-attributes) in the README for those who need to configure a service login.

Here's the scary part: I currently only have my mac to work on, so I still cannot properly test this. I've published it as `1.0.0-beta.5`. I appreciate the help from all of you who are testing this out and providing feedback!

**Comment by devcshort** [comment]
> Based on @forty's experience, I've made the `allowservicelogin` configuration attribute optional (off by default), as it appears the problem is with the winsw config being generated. There is now a [note](https://github.com/coreybutler/node-windows#user-account-attributes) in the README for those who need to configure a service login.
> 
> Here's the scary part: I currently only have my mac to work on, so I still cannot properly test this. I've published it as `1.0.0-beta.5`. I appreciate the help from all of you who are testing this out and providing feedback!

Just tested it out on our local test server. It seems to be working as intended on beta 5. Ran an uninstall. Then ran our regular install script and it's showing in the service manager and is accessible from other computers within the network as intended.

**Comment by forty** [comment]
I also confirm beta.5 works here :+1:

**Comment by Perlkonig** [comment]
Confirmed here too.

**Comment by coreybutler** [comment]
Thanks to everyone who helped flesh out this issue/provide feedback!
